// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfUZ642Aib2Ery_1vNlUS4SmfMUUPDA2U',
    appId: '1:516147692554:web:1ea14531b2c56f77368bf3',
    messagingSenderId: '516147692554',
    projectId: 'visiting2-6e83e',
    authDomain: 'visiting2-6e83e.firebaseapp.com',
    storageBucket: 'visiting2-6e83e.firebasestorage.app',
    measurementId: 'G-3EK4ZV5RW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxwVug1UZhAYO3zRnukCu2bTKlnmghPw',
    appId: '1:516147692554:android:7a631d70ed216259368bf3',
    messagingSenderId: '516147692554',
    projectId: 'visiting2-6e83e',
    storageBucket: 'visiting2-6e83e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzPOUny7U1Wadp6H8yEiNZtnCTFueKdeE',
    appId: '1:516147692554:ios:0086844620490aa2368bf3',
    messagingSenderId: '516147692554',
    projectId: 'visiting2-6e83e',
    storageBucket: 'visiting2-6e83e.firebasestorage.app',
    iosBundleId: 'com.example.visitingV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzPOUny7U1Wadp6H8yEiNZtnCTFueKdeE',
    appId: '1:516147692554:ios:0086844620490aa2368bf3',
    messagingSenderId: '516147692554',
    projectId: 'visiting2-6e83e',
    storageBucket: 'visiting2-6e83e.firebasestorage.app',
    iosBundleId: 'com.example.visitingV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfUZ642Aib2Ery_1vNlUS4SmfMUUPDA2U',
    appId: '1:516147692554:web:c1e47ba4c2caa721368bf3',
    messagingSenderId: '516147692554',
    projectId: 'visiting2-6e83e',
    authDomain: 'visiting2-6e83e.firebaseapp.com',
    storageBucket: 'visiting2-6e83e.firebasestorage.app',
    measurementId: 'G-Z3DC2CZBDG',
  );
}
